# Copyright 2024 Jamie Wilkinson.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""Defines a repository rule containing a canonical DejaGNU toolchain."""

TOOLCHAIN_BUILD = """\
# Generated by @rules_dejagnu/dejagnu/internal:toolchain_repository.bzl
load("@rules_dejagnu//dejagnu/internal:toolchain_type.bzl", "DEJAGNU_TOOLCHAIN_TYPE")

toolchain(
    name = "toolchain",
    toolchain = {dejagnu_repo_name} + "//toolchain:toolchain_info",
    toolchain_type = DEJAGNU_TOOLCHAIN_TYPE,
    visibility = ["//visibility:public"],
)
"""

def _dejagnu_toolchain_repository_impl(repository_ctx):
    repository_ctx.file("BUILD.bazel", TOOLCHAIN_BUILD.format(dejagnu_repo_name = repr(repository_ctx.attr.dejagnu_repository)))

dejagnu_toolchain_repository = repository_rule(
    implementation = _dejagnu_toolchain_repository_impl,
    doc = """\
    Toolchain repository rule for DejaGNU toolchains.
    """,
    attrs = {
        "dejagnu_repository": attr.string(
            doc = "The name of a [`dejagnu_repository`](#dejagnu_repository).",
            mandatory = True,
        ),
    },
)
